//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int notId { get; set; }
        public string message { get; set; }
        public string url { get; set; }
        public bool unseen { get; set; }
        public int userId { get; set; }
    
        public virtual User User { get; set; }
    }
}
