// <auto-generated />
namespace MVCVideo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Initialmod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialmod));
        
        string IMigrationMetadata.Id
        {
            get { return "201809110415224_Initialmod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
